<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>Loan Payment Transaction Report</title>
        <style>
            body {
                font-family: "DejaVu Sans", sans-serif;
                font-size: 12px;
                color: #111;
                margin: 24px;
            }
            .header {
                display: flex;
                justify-content: space-between;
                align-items: center;
                border-bottom: 1px solid #cfcfcf;
                padding-bottom: 12px;
                margin-bottom: 16px;
            }
            .logo {
                height: 40px;
            }
            .company {
                text-align: right;
                font-size: 12px;
            }
            h1 {
                font-size: 18px;
                margin: 0 0 8px 0;
            }
            .meta {
                margin-bottom: 16px;
            }
            .meta-row {
                display: flex;
                justify-content: space-between;
                margin-bottom: 6px;
            }
            .label {
                color: #555;
                font-size: 11px;
                text-transform: uppercase;
            }
            .summary {
                border: 1px solid #e2e2e2;
                padding: 10px;
                margin-bottom: 16px;
            }
            .summary-row {
                display: flex;
                justify-content: space-between;
                margin-bottom: 6px;
            }
            table {
                width: 100%;
                border-collapse: collapse;
            }
            th,
            td {
                border: 1px solid #e2e2e2;
                padding: 6px 8px;
                text-align: left;
                vertical-align: top;
            }
            th {
                background: #f5f5f5;
                font-size: 10px;
                text-transform: uppercase;
                letter-spacing: 0.04em;
            }
            .text-right {
                text-align: right;
            }
            .footer {
                margin-top: 18px;
                font-size: 10px;
                color: #666;
            }
        </style>
    </head>
    <body>
        @php
            $formatCurrency = fn ($value) => $value === null ? '--' : number_format((float) $value, 2);
            $formatDate = fn ($value) => $value ? \Illuminate\Support\Carbon::parse($value)->toDateString() : '--';
        @endphp

        <div class="header">
            <div>
                @if ($logoData)
                    <img src="{{ $logoData }}" alt="Company logo" class="logo" />
                @endif
            </div>
            <div class="company">
                <div>{{ $companyName }}</div>
                <div>Loan Payment Transaction Report</div>
            </div>
        </div>

        <h1>Loan Payment Transaction Report</h1>

        <div class="meta">
            <div class="meta-row">
                <div>
                    <div class="label">Member Name</div>
                    <div>{{ $memberName }}</div>
                </div>
                <div>
                    <div class="label">Member Account No</div>
                    <div>{{ $memberAccountNo ?? '--' }}</div>
                </div>
            </div>
            <div class="meta-row">
                <div>
                    <div class="label">Loan Number</div>
                    <div>{{ $loanNumber }}</div>
                </div>
                <div>
                    <div class="label">Report Period</div>
                    <div>{{ $reportStart->toDateString() }} - {{ $reportEnd->toDateString() }}</div>
                </div>
            </div>
            <div class="meta-row">
                <div>
                    <div class="label">Generated At</div>
                    <div>{{ $generatedAt->toDateTimeString() }}</div>
                </div>
                <div>
                    <div class="label">Generated By</div>
                    <div>{{ $generatedBy ?? '--' }}</div>
                </div>
            </div>
        </div>

        <div class="summary">
            <div class="summary-row">
                <span class="label">Opening Balance</span>
                <span>{{ $formatCurrency($openingBalance) }}</span>
            </div>
            <div class="summary-row">
                <span class="label">Closing Balance</span>
                <span>{{ $formatCurrency($closingBalance) }}</span>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Transaction Date</th>
                    <th>Reference No</th>
                    <th>Loan Type</th>
                    <th class="text-right">Principal</th>
                    <th class="text-right">Payment</th>
                    <th class="text-right">Debit</th>
                    <th class="text-right">Credit</th>
                    <th class="text-right">Balance</th>
                    <th class="text-right">Accrued Interest</th>
                    <th>Status</th>
                    <th>Control No</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($payments as $row)
                    <tr>
                        <td>{{ $formatDate($row->date_in) }}</td>
                        <td>{{ $row->mreference ?? $row->transno ?? $row->controlno ?? '--' }}</td>
                        <td>{{ $row->lntype ?? '--' }}</td>
                        <td class="text-right">{{ $formatCurrency($row->principal) }}</td>
                        <td class="text-right">{{ $formatCurrency($row->payments) }}</td>
                        <td class="text-right">{{ $formatCurrency($row->debit) }}</td>
                        <td class="text-right">{{ $formatCurrency($row->credit) }}</td>
                        <td class="text-right">{{ $formatCurrency($row->balance) }}</td>
                        <td class="text-right">{{ $formatCurrency($row->accruedint) }}</td>
                        <td>{{ $row->lnstatus ?? '--' }}</td>
                        <td>{{ $row->controlno ?? '--' }}</td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="11">No transactions found for this period.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <div class="footer">
            Report period: {{ $reportStart->toDateString() }} - {{ $reportEnd->toDateString() }}
        </div>

        <script type="text/php">
            if (isset($pdf)) {
                $font = $fontMetrics->getFont("DejaVu Sans");
                $size = 9;
                $text = "Page {PAGE_NUM} of {PAGE_COUNT}";
                $width = $fontMetrics->getTextWidth($text, $font, $size);
                $x = $pdf->get_width() - $width - 36;
                $y = $pdf->get_height() - 28;
                $pdf->page_text($x, $y, $text, $font, $size, [0, 0, 0]);
            }
        </script>
    </body>
</html>
